@startuml

class Game
class Players
Players : static ArrayList<Players> playerList
Players : int currentPoints
Players : String name

class Cards
Cards : static ArrayList<Card> cardList
Cards : String id
Cards : boolean paired
Cards : boolean inGame

class CardsInGame


class Round

note "clone objects" as  N1
Cards .. N1
N1 .. CardsInGame

Game <.. Players
Round <.. Players
Game <-- Round
Cards <.. CardsInGame

@enduml